version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./back:/var/www/html

  mysql:
    image: mysql:8.0.20
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --default-authentication-plugin=mysql_native_password

    volumes:
    - ./data/data:/var/lib/mysql

    ports:
    - ${DB_PORT}:3306

  # phpmyadminのコンテナを作成する場合。ただ、わざわざコンテナ作成しなくても無料ツールのworkbenchなどで代用できる。
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql #mysqlサービス名を指定
  #     - PMA_USER=${PMA_USER}
  #     - PMA_PASSWORD=${PMA_PASS}
  #   links:
  #     - mysql
  #   ports:
  #     - ${PMA_PORT}:80
  #   volumes:
  #     - ./phpmyadmin/sessions:/sessions